### ISSUE TITLE
icons are not clickable 

### ISSUE THREAD

**Issue by rafitc** [hackclub-cucek/v4#14]
Make that social icons into clickable icons.

**Comment by superRaptor911** [comment]
Links are not provided

**Comment by superRaptor911** [comment]
Please provide links

**Comment by rafitc** [comment]
@SuvarneshKM can you provide all social links?

**Comment by SuvarneshKM** [comment]
Done

**Comment by rafitc** [comment]
Any updates on this issue @superRaptor911

**Comment by superRaptor911** [comment]
Fixed in latest pr
